### ISSUE TITLE
Change color to match DataFest2022 branding

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#14]
This is a test task for changing colors

**Comment by goodtocode** [comment]
Here is the line in the timeline: Apply DataFest brand, color, logo, fonts site-wide. 
Branding files here: https://github.com/datafestafrica/files/tree/main/branding
* Colors need some serious help. 
* Font is already applied, but may need styling improvement.

Thanks for the help!

**Comment by Gift-Ojeabulu** [comment]
Nice
