### ISSUE TITLE
Registration - Expose registration link and description

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#16]
Goal: Expose at least the link and description text to Registration section

**Comment by usmahm** [comment]
Do we have the backend ready for this already? @goodtocode

**Comment by goodtocode** [comment]
> Do we have the backend ready for this already? @goodtocode

Unfortunately no. Eventbrite was the favorite, but it does not seem to support naira. @David-abu is looking for another. Do you know of any event platforms that support african-friendly payment processors, like PayStack?

**Comment by goodtocode** [comment]
Information from @David-abu: 
Registration link: https://eventprime.co/e/datafestafrica
