### ISSUE TITLE
Sponsors - Add Logo, Name and link to their URL

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#22]
Add Logo, Name and link to their URL

Display Sponsor images underneath a title that specifies what sponsorship level they have

Gold, Silver Bronze header with logos underneath

**Comment by Divyansh-0** [comment]
Can you elaborate what to do??

**Comment by goodtocode** [comment]
> Can you elaborate what to do??

You bet. This is expected to be an iterative process:
1. Get 1st set of Sponsor data in from @David-abu and/or @Gift-Ojeabulu 
2. Uncomment design example of Logos index.html - Line 228
3. Add Sponsor Level headers above each set of logos. I.e. Platinum vs. Gold vs. Silver vs. Bronze. This "level" will be supplied with data.
4. Replace images with logo given from step 1 
5. Replace URL with url given in step 1
6. Optionally - Add a hover-over bio or add blurb underneath logo (if requested from David/Gift. Otherwise, logo+URL is fine.)

As we get more data, let's repeat the process.

FUTURE: We can create a sponsors.html page that highlights sponsors. An option to consider.

Thanks so much for your contributions!
Robert
