### ISSUE TITLE
1.0 GO LIVE DataFestAfrica.com (5/1 at 00:00 WAT)

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#25]
Change DNS to point to PROD site.

**Comment by goodtocode** [comment]
Create /pipelines and /infrastructure as well.

**Comment by goodtocode** [comment]
@David-abu @Gift-Ojeabulu , Azure Dev environment infrastructure installed and CI/CD pipelines working. Files in .github/infrastructure and .github/pipelines. Next is source, then will deploy to prod to prepare it for the DNS cutover. 
![image](https://user-images.githubusercontent.com/6877973/165389104-45b64445-b7c1-4678-9a32-eea06debe9b8.png)

**Comment by goodtocode** [comment]
Azure Dev Site up https://web-www-dev-2022.azurewebsites.net/
![image](https://user-images.githubusercontent.com/6877973/165390708-df095fd9-0ad7-45fb-95a3-f20bd7b91fb1.png)

**Comment by goodtocode** [comment]
Prod infrastructure up: https://web-www-prod-2022.azurewebsites.net/
![image](https://user-images.githubusercontent.com/6877973/165396382-3babf090-c6f5-41b0-bab1-d83b566cde33.png)

**Comment by goodtocode** [comment]
Azure PROD - rg-www-prod-2022
1. SSL PFX Purchased
2. DataFestAfrica.com registered as custom domain
3. www.DataFestAfrica.com registered as custom domain
Tested both https://datafestafrica.com and https://www.datafestafrica.com - DNS Propagation Working

@David-abu @Gift-Ojeabulu Plan to forward these 2 URLs back to twitter at about midnight WAT. Can see the DNS working for another 1.5 hours before the 302 redirect goes into place. (https://twitter.com/search?q=%23DATAFESTAFRICA2022&src=typed_query)

**Comment by goodtocode** [comment]
![image](https://user-images.githubusercontent.com/6877973/165414455-e840725a-00fa-4bfa-a694-e7df48d08d55.png)
302 (temporary) redirection to twitter in-place. Will route to web site upon GO LIVE approval. @David-abu

**Comment by David-abu** [comment]
> Azure Dev Site up https://web-www-dev-2022.azurewebsites.net/ ![image](https://user-images.githubusercontent.com/6877973/165390708-df095fd9-0ad7-45fb-95a3-f20bd7b91fb1.png)

it should be #DatafestAfrica2022

**Comment by goodtocode** [comment]
![image](https://user-images.githubusercontent.com/6877973/165977519-a00e1eb5-12ab-40a5-8790-9c3f24d92d34.png)
