### ISSUE TITLE
Mobile: logo stays on screen at scroll, hide it

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#70]
Mobile logo stays on screen at scroll, hide it if possible

**Comment by Divyansh-0** [comment]
Do you want the logo to hide like the other navigation options such as home , etc??

**Comment by Divyansh-0** [comment]
If some one will clarify how the logo is meant to be displayed?? then it would be great.

**Comment by Divyansh-0** [comment]
I have shifted the logo for mobile devices Check once #90

**Comment by goodtocode** [comment]
This looks fantastic @Divyansh-0 ! Let me run it by the group to see if they like this direction, or if an always-present-logo is preferred over no logo. Personally, I think this is much cleaner.

**Comment by Divyansh-0** [comment]
OK also can you tell where i can discuss my inputs  for the projects

**Comment by goodtocode** [comment]
> OK also can you tell where i can discuss my inputs for the projects

You bet, @David-abu is leading the organization and event, @Gift-Ojeabulu is leading the web site development.

**Comment by Divyansh-0** [comment]
thank you @goodtocode

**Comment by goodtocode** [comment]
Hi @Divyansh-0, we are going to put this change on the shelf. Seems that the leadership became fond of the logo on-screen, we'll leave it there for the time being. Sorry about the UAT cycle not approving, but that is the way of branding changes. Bugs are always approved, branding and UX is not so guaranteed ;(
