### ISSUE TITLE
Mobile: Youtube videos are not responsive

### ISSUE THREAD

**Issue by goodtocode** [datafestafrica/datafestafrica.github.io#73]
In Mobile, Youtube videos are not responsive

Goal: center/right-size

**Comment by Divyansh-0** [comment]
i made it responsive check my pull request and let me know

**Comment by Divyansh-0** [comment]
#77

**Comment by the-timoye** [comment]
Hello, is this sorted? Can we have it assigned (if someone's working on it) so we don't have a clash?

**Comment by goodtocode** [comment]
Resolved by 
https://github.com/datafestafrica/datafestafrica.github.io/pull/80
https://github.com/datafestafrica/datafestafrica.github.io/pull/77
